/** Declaration file generated by dts-gen */

export = jsx_render_to_html;

/**
 * 转换 jsx 文件成 html 文件
 */
declare function jsx_render_to_html(jsxPath: string, htmlPath: string, options: any): void;
